require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe V1::BindersController, type: :controller do

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BindersController. Be sure to keep this updated too.
  let(:user) {
    create(:user)
  }
  before :each do
    request.headers.merge!({ 'Authorization' => user.access_token })
  end

  let!(:binder) { create :binder, user_id: user.id }
  let!(:unauthorized_binder) { create :binder, user_id: nil }

  describe "GET #index" do
    it "assigns all binders as @binders" do
      get :index, {}
      expect(assigns(:binders)).to eq([binder])
    end

    it "returns a successful 200 response" do
      get :index, {}
      expect(response).to be_success
    end

    context "with nested links" do
      it "it has_many links associated with @binders" do
        link1 = create(:link)
        link2 = create(:link)
        binder.links << link1
        binder.links << link2
        get :index, {}
        expect(assigns(:binders)[0].links).to eq([link1, link2])
      end
    end

  end

  describe "GET #show" do
    it "assigns the requested binder as @binder" do
      get :show, {:id => binder.to_param}
      expect(assigns(:binder)).to eq(binder)
    end

    it "returns an error if the binder is not found" do
      get :show, {:id => "999999"}
      expect(response).to be_not_found
    end

    it "returns unauthorized current user does not own binder" do
      get :show, {:id => unauthorized_binder.id}
      expect(response).to be_unauthorized
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Binder" do
        expect {
          post :create, { :binder => attributes_for(:binder) }
        }.to change(Binder, :count).by(1)
      end

      it "assigns a newly created binder as @binder" do
        post :create, { :binder => attributes_for(:binder) }
        expect(assigns(:binder)).to be_a(Binder)
        expect(assigns(:binder)).to be_persisted
      end

      it "responds with http status created" do
        post :create, { :binder => attributes_for(:binder) }
        expect(response).to be_created
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved binder as @binder" do
        post :create, { :binder => attributes_for(:invalid_binder) }
        expect(assigns(:binder)).to be_a_new(Binder)
      end

      it "responds with HTTP unprocessable_entity" do
        post :create, { :binder => attributes_for(:invalid_binder) }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) { {
        "name" => "test_new_name"
      } }

      it "updates the requested binder" do
        put :update, {:id => binder.to_param, :binder => new_attributes}
        binder.reload
        expect(binder.name).to eq "test_new_name"
      end

      it "assigns the requested binder as @binder" do
        put :update, {:id => binder.to_param, :binder => attributes_for(:binder)}
        expect(assigns(:binder)).to eq(binder)
      end

      it "responds with HTTP no_content" do
        put :update, {:id => binder.to_param, :binder => attributes_for(:binder)}
        expect(response).to have_http_status(:no_content)
      end
    end

    context "with invalid params" do
      it "assigns the binder as @binder" do
        put :update, {:id => binder.to_param, :binder => attributes_for(:invalid_binder)}
        expect(assigns(:binder)).to eq(binder)
      end

      it "responds with HTTP unprocessable_entity" do
        put :update, {:id => binder.to_param, :binder => attributes_for(:invalid_binder)}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested binder" do
      expect {
        delete :destroy, {:id => binder.to_param}
      }.to change(Binder, :count).by(-1)
    end

    it "responds with HTTP no_content" do
      delete :destroy, {:id => binder.to_param}
      expect(response).to have_http_status(:no_content)
    end
  end

end
