# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3089e26907eda3043203b823f46f36d94496c17f84e3818b4618dd9a50ff2585411c1498c40d99edf758db5cbbb4f0b12a37c76579ac48809ddb7c9464bf72bb

test:
  secret_key_base: 17dadbf111f339c68966e91ba8793b499c4f68ee54a38452d074718043990655f73cbfa59403555dc25b460e4707888ebabf807b88a5f501e7ddc0a868b6bd8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
